import os
import re
import time
from typing import Optional

from app.db.cookie_dao import delete_cookie, get_cookie_row, upsert_cookie
from app.utils.logger import get_logger

logger = get_logger(__name__)

USER_COOKIE_DIR = os.path.join(os.getenv("DATA_DIR", "data"), "user_cookies")
USER_COOKIE_FILES = {
    "bilibili": os.path.join(USER_COOKIE_DIR, "bilibili.txt"),
}
ALLOWED_PLATFORMS = frozenset(USER_COOKIE_FILES.keys())
_PLATFORM_RE = re.compile(r"^[A-Za-z0-9_-]{1,32}$")

_BILI_SECURE_KEYS = {"SESSDATA", "bili_jct", "DedeUserID", "DedeUserID__ckMd5"}
_AUTH_ERROR_MARKERS = (
    "412", "403", "login", "cookie", "sign in", "authentication",
    "登录", "大会员", "授权", "forbidden", "permission", "access denied",
)


class DownloadAuthError(Exception):
    """下载需要登录/Cookie。"""

    def __init__(self, message: str, platform: str = "bilibili"):
        super().__init__(message)
        self.platform = platform


def is_auth_error(err: Exception) -> bool:
    msg = str(err).lower()
    return any(marker in msg for marker in _AUTH_ERROR_MARKERS)


def to_netscape_cookie_text(raw: str, domain: str = ".bilibili.com") -> str:
    """接受 Netscape cookies.txt 或 Cookie 请求头字符串，统一成 yt-dlp 可用格式。"""
    raw = (raw or "").strip()
    if not raw:
        raise ValueError("Cookie 内容为空")

    head = raw[:120].lower()
    if "netscape" in head or "http cookie file" in head or raw.lstrip().startswith("#"):
        lines = [ln for ln in raw.splitlines() if ln.strip()]
        if not any("\t" in ln and not ln.lstrip().startswith("#") for ln in lines):
            raise ValueError("cookies.txt 格式无效，请重新导出")
        return raw if raw.endswith("\n") else raw + "\n"

    pairs = []
    for part in raw.split(";"):
        part = part.strip()
        if not part or "=" not in part:
            continue
        name, value = part.split("=", 1)
        name, value = name.strip(), value.strip()
        if name:
            pairs.append((name, value))

    if not pairs:
        raise ValueError(
            "无法识别 Cookie 格式。请粘贴 Netscape cookies.txt 全文，"
            "或浏览器里的 Cookie 请求头（形如 SESSDATA=xxx; bili_jct=yyy）"
        )

    names = {n for n, _ in pairs}
    if "SESSDATA" not in names:
        raise ValueError("缺少 SESSDATA，请确认已登录 B 站后再复制 Cookie")

    expire = str(int(time.time()) + 180 * 86400)
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by BiliNote user cookie config",
    ]
    for name, value in pairs:
        secure = "TRUE" if name in _BILI_SECURE_KEYS else "FALSE"
        lines.append(f"{domain}\tTRUE\t/\t{secure}\t{expire}\t{name}\t{value}")
    return "\n".join(lines) + "\n"


def _mask_secret(text: str, keep: int = 6) -> str:
    if not text:
        return ""
    if len(text) <= keep * 2:
        return text[:keep] + "…"
    return f"{text[:keep]}…{text[-keep:]}"


def _user_cookie_path(platform: str) -> str:
    safe = _sanitize_platform(platform)
    return USER_COOKIE_FILES[safe]


def _sanitize_platform(platform: str) -> str:
    platform = (platform or "").strip().lower()
    if platform not in ALLOWED_PLATFORMS or not _PLATFORM_RE.match(platform):
        raise ValueError(f"暂不支持的平台：{platform or '(空)'}，目前仅支持: {', '.join(sorted(ALLOWED_PLATFORMS))}")
    return platform


def settings_url() -> str:
    port = os.getenv("BACKEND_PORT", "8000")
    host = os.getenv("BACKEND_HOST", "127.0.0.1")
    if host in ("0.0.0.0", "::", ""):
        host = "127.0.0.1"
    return f"http://{host}:{port}/cookie.html"


class CookieService:
    """平台 Cookie 自助配置：网页保存 → 本地文件 + SQLite；下载时无 Cookie 优先。"""

    @staticmethod
    def save_cookie(platform: str, cookie_text: str) -> dict:
        platform = _sanitize_platform(platform)
        netscape = to_netscape_cookie_text(cookie_text)
        path = _user_cookie_path(platform)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(netscape)
        ok = upsert_cookie(platform, netscape, enabled=1)
        if not ok:
            raise RuntimeError("保存 Cookie 到数据库失败")
        sess = ""
        for line in netscape.splitlines():
            if "SESSDATA" in line and not line.lstrip().startswith("#"):
                parts = line.split("\t")
                if len(parts) >= 7:
                    sess = parts[-1]
                    break
        return CookieService.get_status(platform)

    @staticmethod
    def clear_cookie(platform: str) -> dict:
        platform = _sanitize_platform(platform)
        path = _user_cookie_path(platform)
        if os.path.exists(path):
            try:
                os.remove(path)
            except OSError as e:
                logger.warning(f"删除用户 Cookie 文件失败: {e}")
        delete_cookie(platform)
        return CookieService.get_status(platform)

    @staticmethod
    def get_status(platform: str) -> dict:
        platform = _sanitize_platform(platform)
        user_path = _user_cookie_path(platform)
        row = get_cookie_row(platform)
        user_configured = bool(row and row[2] == 1) and os.path.exists(user_path)

        env_file = os.getenv("COOKIE_FILE", "") or ""
        env_file_ok = bool(env_file) and os.path.exists(env_file)
        env_browser = os.getenv("COOKIES_FROM_BROWSER", "") or ""

        source = "none"
        if user_configured:
            source = "user"
        elif env_file_ok:
            source = "env_file"
        elif env_browser:
            source = "env_browser"

        preview = ""
        if user_configured:
            try:
                with open(user_path, "r", encoding="utf-8") as f:
                    for line in f:
                        if "SESSDATA" in line and not line.lstrip().startswith("#"):
                            parts = line.split("\t")
                            if len(parts) >= 7:
                                preview = _mask_secret(parts[-1].strip())
                                break
            except OSError:
                preview = ""
        elif env_file_ok:
            preview = f"(来自环境变量文件 {env_file})"
        elif env_browser:
            preview = f"(来自本机浏览器 {env_browser})"

        return {
            "platform": platform,
            "configured": source != "none",
            "user_configured": user_configured,
            "source": source,
            "preview": preview,
            "user_cookie_file": os.path.basename(user_path) if user_configured else None,
            "settings_url": settings_url(),
            "updated_at": row[3] if row else None,
            "policy": "no-cookie-first",
        }

    @staticmethod
    def resolve_cookiefile(platform: str, prefer_user: bool = True) -> Optional[str]:
        """返回可用于 yt-dlp 的 cookie 文件路径；都没有则 None。"""
        platform = _sanitize_platform(platform)
        user_path = _user_cookie_path(platform)
        row = get_cookie_row(platform)
        if prefer_user and row and row[2] == 1 and os.path.exists(user_path):
            return user_path

        env_file = os.getenv("COOKIE_FILE", "") or ""
        if env_file and os.path.exists(env_file):
            return env_file

        if not prefer_user and row and row[2] == 1 and os.path.exists(user_path):
            return user_path
        return None

    @staticmethod
    def resolve_cookiesfrombrowser() -> Optional[str]:
        return os.getenv("COOKIES_FROM_BROWSER", "") or None

    @staticmethod
    def auth_error_message(platform: str) -> str:
        platform = _sanitize_platform(platform)
        status = CookieService.get_status(platform)
        url = settings_url()
        if status["configured"]:
            return (
                f"{platform} 下载仍失败（可能是 Cookie 过期或权限不足）。"
                f"请打开 {url} 更新 Cookie 后重试。"
            )
        return (
            f"{platform} 该视频需要登录才能下载（公开视频通常无需 Cookie）。"
            f"请打开 {url} 自助配置 Cookie 后重试。"
        )
